name: Build, Test, and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image
      run: docker build -t my-accounts-service .

    - name: Run Docker container
      run: docker run -d -p 5001:8080 --name accounts-container my-accounts-service
      
    - name: Wait for the service to be up
      run: sleep 30
      
    - name: View Docker logs
      run: docker logs accounts-container
      
    - name: Test the running container
      run: |
        curl --retry 2 --retry-delay 10 --retry-connrefused http://localhost:8080/api/ping

    - name: Stop and remove Docker container
      run: |
        docker stop accounts-container
        docker rm accounts-container
